### ISSUE TITLE
brewed python on Ubuntu 14.04.1 LTS doesn't include _ssl.so so pip is broken

### ISSUE THREAD

**Issue by harper357** [Homebrew/linuxbrew#188]
Not exactly sure the best way to describe this problem. Even after a clean `brew install python`, there is no _ssl.so in ~/.linuxbrew/Cellar/python/2.7.8_2/lib/python2.7/lib-dynload 

This is resulting in pip giving me the following error 
```
% pip
Traceback (most recent call last):
  File "/data/gfedewa/.linuxbrew/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 356, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2476, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2190, in load
  File "/data/gfedewa/.linuxbrew/opt/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/__init__.py", line 10, in <module>
    from pip.util import get_installed_distributions, get_prog
  File "/data/gfedewa/.linuxbrew/opt/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 18, in <module>
    from pip._vendor.distlib import version
  File "/data/gfedewa/.linuxbrew/opt/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/distlib/version.py", line 14, in <module>
    from .compat import string_types
  File "/data/gfedewa/.linuxbrew/opt/python/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
```

I have the brewed version of Openssl, and there is a system version of Openssl.

gist: https://gist.github.com/1f99d3ef0c1db6836502

**Comment by hbetts** [comment]
@sjackman I haven't tried crossing my fingers yet, but after several re-installations of Python the installation has just decided to work.

The only difference in my process is to install `brew install openssl` first, then install python via `brew install python --with-brewed-openssl`.

**Comment by sjackman** [comment]
Glad to hear that you got it working! Python doesn't have a `--with-brewed-openssl` option though. I wonder if that option might have applied to one of its dependencies. It uses the brewed openssl by default.

**Comment by prologic** [comment]
So this is an issue for me as well. I only very recently installed brewlinux and Python and have run into the exact same problem. @sjackman You are right about there being no ``--with-brewed-openssl`` option so I'm a little confused as to *what the actual solution is*.

**Comment by prologic** [comment]
FWIW:

```#!bash
prologic@dev5973
Fri Oct 16 07:29:35
~/.linuxbrew
 (master)
$ find . | grep failed
./share/doc/homebrew/brew-test-bot-failed-jenkins.png
./share/doc/homebrew/brew-test-bot-failed-pr.png
./share/doc/homebrew/brew-test-bot-failed-test.png
./Cellar/python/2.7.10_2/lib/python2.7/lib-dynload/dbm_failed.so
./Cellar/python/2.7.10_2/lib/python2.7/lib-dynload/_ssl_failed.so
./lib/python2.7/lib-dynload/_ssl_failed.so
./lib/python2.7/lib-dynload/dbm_failed.so
```

**Comment by sjackman** [comment]
@Homebrew/linux Anyone have a solution for the Python `_ssl_failed.so` issue?

**Comment by sjackman** [comment]
Let's move this discussion to #420.
