### ISSUE TITLE
ruby : problem with rails

### ISSUE THREAD

**Issue by heejongahn** [Homebrew/linuxbrew#240]
Hi. I'm running Ubuntu Server 14.04.1 LTS on my VirtualBox VM (my physical machine is using Windows 8.1) and I have a problem with rails (on my VM). I downloaded ruby 2.2.0p0 using linuxbrew and ran `gem install rails` and `bundle` in my Rails project folder. After that, I tried to `rails server` but following message came out : 

```
bin/rails:6: warning: already initialized constant APP_PATH
/home/nobell/web-boilerplate/server/bin/rails:6: warning: previous definition of APP_PATH was here
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information.
```

To find out what's happening, I inserted `puts APP_PATH` after the line 6 of /bin/rails and following message came out:

```
/home/nobell/web-boilerplate/server/config/application
bin/rails:6: warning: already initialized constant APP_PATH
/home/nobell/web-boilerplate/server/bin/rails:6: warning: previous definition of APP_PATH was here
/home/nobell/web-boilerplate/server/config/application
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information.
```

As the `APP_PATH` is printed twice, I guessed rails also is probably executed twice... but I have no idea why. I also searched for solution for the problem above and found several posts suggesting `rake rails:update:bin` command. So I tried it and another error message came out:

```
rake aborted!
LoadError: cannot load such file -- readline
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/history.rb:1:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/history.rb:1:in `<top (required)>'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/interface.rb:1:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/interface.rb:1:in `<top (required)>'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/core.rb:5:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug/core.rb:5:in `<top (required)>'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug.rb:1:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/byebug-3.5.1/lib/byebug.rb:1:in `<top (required)>'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
/home/nobell/.linuxbrew/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
/home/nobell/web-boilerplate/server/config/application.rb:7:in `<top (required)>'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/nobell/web-boilerplate/server/Rakefile:4:in `<top (required)>'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/nobell/.linuxbrew/Cellar/ruby/2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/nobell/.linuxbrew/bin/rake:33:in `<main>'
``` 

I've already tried installing readline-related packages and 'rb-readline' is clearly in my gem list.(Maybe related to #215?) Due to error message, I guess it has sth to do with linuxbrew. I couldn't specify the crucial point here and these are all I've found out...

**Comment by sjackman** [comment]
Did you install the readline packages using your host package manager or brew? Try `brew install readline`?

I'm afraid I don't have enough time to troubleshoot individual formula. Please post the workaround or solution if you find one.

**Comment by heejongahn** [comment]
I installed several readline packages already - I tried `brew install readline` too. Anyway I'll keep try to find a solution and if I do, I'll post it here. Thanks for your reply!

**Comment by sjackman** [comment]
Try `brew install homebrew/dupes/ncurses`

**Comment by tkling** [comment]
For the readline problem - try running `bundle exec rake rails:update:bin` instead of just `rake rails:update:bin`. It ensures all of the gems in your Gemfile are available to the command, sometimes helps in moments like this when it seems like a dependency should have been loaded.

http://bundler.io/v1.7/bundle_exec.html

**Comment by heejongahn** [comment]
@sjackman 'brew install homebrew/dupes/ncurses' didn't solve the problem.. but thanks!

@tkling Actually I tried some more thing but I couldn't find a solution so now I removed ruby from linuxbrew and just got back to the rvm. However when I come back to this issue or face other problems such as this, I guess your comment will be helpful. Thanks man!

**Comment by sjackman** [comment]
Using `rvm` is a workaround, I suppose, so I'm closing this issue as *wontfix* for now. I'd be interested in hearing the solution if you find one.

**Comment by wgraydev** [comment]
Hey, I'm also running I'm running Ubuntu Server 14.04.1 LTS on a Rackspace server with ruby version ruby 2.1.2p95. I was getting the same error when tying to run `sudo bundle exec rake db:migrate`. I added `gem 'rb-readline' ` to my Gemfile and ran `bundle install`. Afterward, I was able to run my command.

**Comment by sjackman** [comment]
Nice. Thanks, Landon. @heejongahn Does this `rb-readline` solution work for you?
