### ISSUE TITLE
brew test XXXX => Error: cannot load such file -- minitest/unit

### ISSUE THREAD

**Issue by tseemann** [Homebrew/linuxbrew#314]
This occurs for whatever I try to test:

```
% brew test muscle

Error: cannot load such file -- minitest/unit
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/ruby/test/unit/assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/bio/linuxbrew/Library/Homebrew/formula_assertions.rb:7:in `rescue in <module:Assertions>'
/bio/linuxbrew/Library/Homebrew/formula_assertions.rb:4:in `<module:Assertions>'
/bio/linuxbrew/Library/Homebrew/formula_assertions.rb:2:in `<module:Homebrew>'
/bio/linuxbrew/Library/Homebrew/formula_assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/bio/linuxbrew/Library/Homebrew/cmd/test.rb:4:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/bio/linuxbrew/Library/brew.rb:58:in `require?'
/bio/linuxbrew/Library/brew.rb:117:in `<main>'
```

**Comment by sjackman** [comment]
This bug refuses to die. I am not a fan. `brew install ruby` should fix it. Otherwise, please report `which -a ruby` and `ruby --version`.

**Comment by sjackman** [comment]
@jacknagel Do you recall the cause of `Error: cannot load such file -- minitest/unit`?

**Comment by jacknagel** [comment]
What version of ruby?

**Comment by tseemann** [comment]
Before:
```
/usr/bin/ruby
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
```
Let's *try* the brew version:

```
% brew install ruby
==> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/bio/linuxbrew/Cellar/ruby/2.2.1 --enable-shared --disable-silent-rules --with-sitedir=/bio/linuxbrew/lib/ruby/site
==> make
==> make install
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH (https://github.com/Homebrew/homebrew/issues/33705)
Adding formulas for ndenv and node-build. Inspired by rbenv and ruby-build formulas. (https://github.com/Homebrew/homebrew/pull/34994)
```

Do I need to remove Ruby from my PATH / system first?

**Comment by sjackman** [comment]
Please report…
```sh
/usr/bin/ruby -e"require 'minitest'"; echo $?
brew install ruby -v
brew gist-logs ruby
```
> Do I need to remove Ruby from my PATH / system first?

No, that's fine.

**Comment by tseemann** [comment]
(i did this 5 days ago but it seems I didn't click on the submit/comment button so here it is now)

```
/usr/bin/ruby -e"require 'minitest'"; echo $?
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- minitest (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
1
```

```
tmp/ruby20150324-117760-v9hnam/ruby-2.2.1/lib/rubygems/package.rb:369:in `initialize': Permission denied @ rb_sysopen - /bio/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/metametameta.rb (Errno::EACCES)
```

gist logs: https://gist.github.com/df055256da8f8a909cbb

**Comment by sjackman** [comment]
Can you confirm that you have write access to this file/folder?
`/bio/linuxbrew/Cellar/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/metametameta.rb`

**Comment by tseemann** [comment]
```/bio/linuxbrew/Cellar/ruby``` does not exist. It seems I don't have brew Ruby installed. I'm guessing that is the problem. Should ruby be a dependency somewhere?

**Comment by sjackman** [comment]
If your system version of ruby is recent enough, it'll work. Otherwise `brew install ruby` is best.

**Comment by sjackman** [comment]
Try…
```sh
gem install minitest
```
or
```
sudo yum install rubygem-minitest
```

**Comment by tseemann** [comment]
@sjackman This error popped up again today on a fresh RHEL/Centos install.

FYI `rubygem-minitest` does not exist as an RPM on RHEL 7.2

**Comment by sjackman** [comment]
What version of Ruby are you using? This bug may be unique to Ruby 1.9.x. I think Ruby 1.8 and Ruby 2.x work. `brew install ruby` should resolve it.

**Comment by dpo** [comment]
@sjackman @tseemann FYI I just had the same issue and `gem install minitest` resolved it for me on a Red Hat system.
