### ISSUE TITLE
Error: user .linuxbrew doesn't exist

### ISSUE THREAD

**Issue by aidylewis** [Homebrew/linuxbrew#331]
Attempting to install neovim on Arch Linux and I get: Error: user .linuxbrew doesn't exist

**Comment by sjackman** [comment]
Please post the exact command that you're attempting to run and the exact error message. You likely forgot the slash between `~/.linuxbrew`. To avoid typos, copy and paste the instructions. See http://brew.sh/linuxbrew

**Comment by aidylewis** [comment]
Hi @sjackman 

```sh
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
$ brew doctor
Error: user .linuxbrew doesn't exist
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/aidy/.linuxbrew/Library/Homebrew/utils.rb:203:in `expand_path'
/home/aidy/.linuxbrew/Library/Homebrew/utils.rb:203:in `block in which'
/home/aidy/.linuxbrew/Library/Homebrew/utils.rb:202:in `each'
/home/aidy/.linuxbrew/Library/Homebrew/utils.rb:202:in `which'
/home/aidy/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1094:in `check_for_bad_python_symlink'
/home/aidy/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1285:in `block in doctor'
/home/aidy/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1283:in `each'
/home/aidy/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1283:in `doctor'
/home/aidy/.linuxbrew/Library/brew.rb:135:in `<main>'
```

**Comment by aidylewis** [comment]
Put ~/.linuxbrew/bin at the beginning of the path and 'brew prune' to fix broken soft links.

**Comment by sjackman** [comment]
Please report

**Comment by sjackman** [comment]
Please report
```sh
echo $PATH
```
There's probably a tilde character in there that shouldn't be in there. Try
```sh
export PATH="$HOME/.linuxbrew/bin:$PATH"
```

**Comment by aidylewis** [comment]
Many thanks for your work and help. It looks like I had broken soft links.
