### ISSUE TITLE
git installation fails

### ISSUE THREAD

**Issue by hammer** [Homebrew/linuxbrew#393]
Gist of logs at https://gist.github.com/anonymous/0a0d736f23b9eff1bc3a.

What I see in my shell:
```
$ brew install git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.4.0.tar.xz
Already downloaded: /hpc/users/hammej03/.cache/Homebrew/git-2.4.0.tar.xz
==> make prefix=/demeter/users/hammej03/.linuxbrew/Cellar/git/2.4.0 sysconfdir=/demeter/users/hammej03/.linuxbrew/etc CC=/usr/bin/gcc CFLAGS=-Os -w -pipe -march=core2 LDFLAGS=-L/demeter/users/hammej03/.l
==> make CC=/usr/bin/gcc CFLAGS=-Os -w -pipe -march=core2 LDFLAGS=-L/demeter/users/hammej03/.linuxbrew/lib -Wl,-rpath,/demeter/users/hammej03/.linuxbrew/lib
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.4.0.tar.xz
Already downloaded: /hpc/users/hammej03/.cache/Homebrew/git--man-2.4.0.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.4.0.tar.xz
Already downloaded: /hpc/users/hammej03/.cache/Homebrew/git--html-2.4.0.tar.xz
Error: can't dup NilClass
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/lib/ruby/1.8/pathname.rb:212:in `dup'
/usr/lib/ruby/1.8/pathname.rb:212:in `initialize'
/demeter/users/hammej03/.linuxbrew/Library/Formula/git.rb:139:in `new'
/demeter/users/hammej03/.linuxbrew/Library/Formula/git.rb:139:in `install'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/build.rb:129:in `install'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/formula.rb:515:in `brew'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/formula.rb:884:in `stage'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/resource.rb:91:in `unpack'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/formula.rb:882:in `stage'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/formula.rb:511:in `brew'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/build.rb:107:in `install'
/demeter/users/hammej03/.linuxbrew/Library/Homebrew/build.rb:179
```

**Comment by sjackman** [comment]
Thanks for the bug report, Jeff.
