### ISSUE TITLE
Bug: Undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by LeeBergstrand** [Homebrew/linuxbrew#421]
```shell
brew install diamond
Error: No available formula for diamond 
Searching formulae...
Searching taps...
Error: undefined method `downcase' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/leebergstrand/.linuxbrew/Library/Homebrew/cmd/search.rb:105:in `search_tap'
/home/leebergstrand/.linuxbrew/Library/Homebrew/cmd/search.rb:98:in `block (2 levels) in search_taps'
```

**Comment by sjackman** [comment]
Thanks for the bug report, Lee.
