### ISSUE TITLE
Error installing libav

### ISSUE THREAD

**Issue by dspstudio** [Homebrew/linuxbrew#449]
```
dsp@localhost:~$ brew install libav
==> Installing dependencies for libav: xz, pkg-config, yasm, faac, lame,
==> Installing libav dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /home/dsp/.cache/Homebrew/xz-5.2.1.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/dsp/.linuxbrew/Cellar/xz/5
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/dsp/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/home/dsp/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:490:in `build'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:190:in `install'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:367:in `install_dependency'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:324:in `block in install_dependencies'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:324:in `each'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:324:in `install_dependencies'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:228:in `compute_and_install_dependencies'
/home/dsp/.linuxbrew/Library/Homebrew/formula_installer.rb:155:in `install'
/home/dsp/.linuxbrew/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/home/dsp/.linuxbrew/Library/Homebrew/cmd/install.rb:83:in `block in install'
/home/dsp/.linuxbrew/Library/Homebrew/cmd/install.rb:83:in `each'
/home/dsp/.linuxbrew/Library/Homebrew/cmd/install.rb:83:in `install'
/home/dsp/.linuxbrew/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
This has popped up on Linux as well? :eyes:. We thought it was an OS X exclusive caused by a software update.

https://github.com/Homebrew/homebrew/issues/39170 - Contains solution, as well.

**Comment by dspstudio** [comment]
Now it works. Thanks.
My linux box is: Linux localhost.com 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DomT4** [comment]
@sjackman Given we have an [OS X specific fix warning](https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/cmd/doctor.rb#L432-L439) about this in `brew doctor` you may wish to tweak it on Linux so it reads something like:

```ruby
def check_tmpdir_sticky_bit
  world_writable = HOMEBREW_TEMP.stat.mode & 0777 == 0777
  if world_writable && !HOMEBREW_TEMP.sticky? then <<-EOS.undent
    #{HOMEBREW_TEMP} is world-writable but does not have the sticky bit set.
    Please run `sudo chmod +t  #{HOMEBREW_TEMP}` in your shell.
  EOS
  end
end
```

Or such.

**Comment by sjackman** [comment]
Thanks for the heads up, Dominyk.
