### ISSUE TITLE
Can't install PMD

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/linuxbrew#579]
Installing PMD on Ubuntu 14.04 fails with the following error:
```
tar -xf /tmp/pmd20151002-6066-1wef7se/pmd-src-5.3.3/pmd-dist/target/pmd-bin-5.3.3.zip
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
/home/bob/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
ErrorDuringExecution: Failure while executing: tar -xf /tmp/pmd20151002-6066-1wef7se/pmd-src-5.3.3/pmd-dist/target/pmd-bin-5.3.3.zip
```

Here's the stack trace:

```
/home/bob/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
/home/bob/.linuxbrew/Library/Homebrew/utils.rb:225:in `safe_system'
/home/bob/.linuxbrew/Library/Formula/pmd.rb:15:in `install'
/home/bob/.linuxbrew/Library/Homebrew/debrew.rb:22:in `block in install'
/home/bob/.linuxbrew/Library/Homebrew/debrew.rb:97:in `debrew'
/home/bob/.linuxbrew/Library/Homebrew/debrew.rb:22:in `install'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:129:in `block in install'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:848:in `block in brew'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:1389:in `block in stage'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:91:in `block in unpack'
/home/bob/.linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/bob/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/usr/lib/ruby/1.9.1/forwardable.rb:201:in `stage'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:1381:in `stage'
/home/bob/.linuxbrew/Library/Homebrew/formula.rb:844:in `brew'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:107:in `install'
/home/bob/.linuxbrew/Library/Homebrew/build.rb:176:in `<main>'
```

According to the manpage for bsdtar, bsdtar *can* open ZIP files, but GNU tar cannot.

This is a really easy fix, so I'll probably submit it myself this weekend.

**Comment by DomT4** [comment]
@sjackman We merged a fix for this upstream at Homebrew, so can close this whenever the repos are synced :)

**Comment by sjackman** [comment]
Thanks, Dominyk.

**Comment by sjackman** [comment]
@danabrand handled the merge last week and is looking into the merge for this week.
