### ISSUE TITLE
Error on `brew test`

### ISSUE THREAD

**Issue by jzjsuper** [Homebrew/linuxbrew#599]
When I run `brew test` it shows the following error. 
```
Error: cannot load such file -- test/unit/assertions
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.linuxbrew/Library/Homebrew/formula_assertions.rb:7:in `rescue in <module:Assertions>'
/home/jzjsuper/.linuxbrew/Library/Homebrew/formula_assertions.rb:4:in `<module:Assertions>'
/home/jzjsuper/.linuxbrew/Library/Homebrew/formula_assertions.rb:2:in `<module:Homebrew>'
/home/jzjsuper/.linuxbrew/Library/Homebrew/formula_assertions.rb:1:in `<top (required)>'
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.linuxbrew/Library/Homebrew/cmd/test.rb:2:in `<top (required)>'
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/jzjsuper/.linuxbrew/Library/brew.rb:60:in `require?'
/home/jzjsuper/.linuxbrew/Library/brew.rb:110:in `<main>'
```

**Comment by DomT4** [comment]
Should be resolved now, providing your brew is up-to-date.
