### ISSUE TITLE
Issue with bottle :unneeded

### ISSUE THREAD

**Issue by iggyvolz** [Homebrew/linuxbrew#660]
The offending line in wpcli-completion is bottle :unneeded.  This seems to work fine with Homebrew but not Linuxbrew.  If it isn't supported then I'll report this issue on homebrew-completions but it seems to be a bug with Linuxbrew.

```$ brew outdated
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/iggyvolz/.linuxbrew/Library/Homebrew/software_spec.rb:72:in `instance_eval'
/home/iggyvolz/.linuxbrew/Library/Homebrew/software_spec.rb:72:in `bottle'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formula.rb:1599:in `bottle'
/home/iggyvolz/.linuxbrew/Library/Taps/homebrew/homebrew-completions/wpcli-completion.rb:9:in `<class:WpcliCompletion>'
/home/iggyvolz/.linuxbrew/Library/Taps/homebrew/homebrew-completions/wpcli-completion.rb:1:in `load_formula'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:165:in `get_formula'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:205:in `factory'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formulary.rb:224:in `from_rack'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formula.rb:1034:in `block in installed'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formula.rb:1032:in `map'
/home/iggyvolz/.linuxbrew/Library/Homebrew/formula.rb:1032:in `installed'
/home/iggyvolz/.linuxbrew/Library/Homebrew/cmd/outdated.rb:7:in `outdated'
/home/iggyvolz/.linuxbrew/Library/brew.rb:145:in `<main>'```

**Comment by sjackman** [comment]
This bug lies in Linuxbrew. @danabrand and @DomT4 are looking into it.

**Comment by DomT4** [comment]
It should be resolved now with the latest merge from testing. Let us know otherwise, Thanks.
