### ISSUE TITLE
Java version dependency seems to be ignored

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/linuxbrew#704]
I tried to upgrade to `golo` version 3 after tonight's merge, having (by coincidence) installed 2.10 this morning.

The upgrade appears to complete successfully, as does uninstalling golo and reinstalling version 3 from scratch. However, in either case, running it is not possible:

    Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/golo/cli/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

The problem seems to be that I'm on Java 7 and golo now depends on Java 8+. However, the build process gives no indication of this, which I suspect means the Java requirement is not checking versions properly.

**Comment by sjackman** [comment]
I don't believe Java version checking is implemented.
Try `brew install jdk`

**Comment by sjackman** [comment]
I'd be happy to accept this feature if you have the time and inclination to submit a pull request.
